services:
  db:
    image: postgres:17
    container_name: inventory_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - inventory_network
    ports:
      - ${DB_PORT}:${DB_PORT}

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inventory_app
    restart: always
    image: inventory
    ports:
      - ${PORT}:${PORT}
    networks:
      - inventory_network
    depends_on:
      - db

volumes:
  postgres_data:

networks:
  inventory_network:
    driver: bridge
