services:
  db:
    image: postgres:17
    container_name: inventory_db_dev
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - inventory_network_dev
    ports:
      - ${DB_PORT}:${DB_PORT}

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: inventory_app_dev
    image: inventory_dev
    ports:
      - ${PORT}:${PORT}
    networks:
      - inventory_network_dev
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  postgres_data_dev:

networks:
  inventory_network_dev:
    driver: bridge
