import type { Metadata } from "next";
import type { PropsWithChildren } from "react";
import { Box } from "@mui/material";
import classNames from "classnames";
import { roboto } from "@/features/theme/fonts";
import { Providers, Sidebar } from "./(components)";
import { getSettings } from "./api/settings/route";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en" className={classNames(roboto.className)}>
      <body>
        <main style={{ height: "100svh" }}>
          <Providers settings={await getSettings()}>
            <Box display="flex" justifyContent="center" height="100%">
              <Box display="grid" gridTemplateColumns="250px 900px" p={3} gap={3}>
                <Sidebar />
                {children}
              </Box>
            </Box>
          </Providers>
        </main>
      </body>
    </html>
  );
}
